# Generated by Django 5.1.5 on 2025-01-24 18:19

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(help_text='Please enter a valid DNS Hostname or IP address', max_length=200, unique=True)),
                ('location', models.CharField(help_text='Please enter the location of the server (PASC, KAD, SDC, etc...)', max_length=200)),
                ('description', models.CharField(help_text='Please enter a brief descriotion of the server', max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('host_name'), name='host_name_case_insensitive_unique', violation_error_message='Host already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular test instance.', primary_key=True, serialize=False)),
                ('test_name', models.CharField(help_text='Please enter a brief descriotion of the test', max_length=200)),
                ('type', models.CharField(blank=True, choices=[('t', 'throughput'), ('l1', 'latency (one-way)'), ('rtt', 'latency (round-trip)'), ('tr', 'traceroute')], default='t', help_text='Test Type', max_length=3)),
                ('test_description', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('source_host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tests.host')),
            ],
        ),
    ]
