# Generated by Django 5.1.5 on 2025-01-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dest_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dest_host', to='tests.host'),
        ),
        migrations.AlterField(
            model_name='test',
            name='source_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='source_host', to='tests.host'),
        ),
    ]
