# Generated by Django 5.1.5 on 2025-01-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_location_alter_host_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_description',
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(help_text='Enter a brief description of the location', max_length=200),
        ),
    ]
