# Generated by Django 5.1.5 on 2025-01-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_test_test_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(help_text='Enter a brief description of the location', max_length=200),
        ),
    ]
